# Generated by Django 3.1 on 2020-08-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200822_1532'),
        ('projects', '0006_auto_20200826_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='navers',
            field=models.ManyToManyField(blank=True, to='users.Naver'),
        ),
    ]
